### ISSUE TITLE
Need help installing addins

### ISSUE THREAD

**Issue by molleraj** [klaumit/CaleidLink#1]
Hi klaumit and thank you so much for making this available to the community! I had a quick question about how you install addins. I followed the directions in README.en and eventually got a successful synchronization of my PV-S400 Plus with the following ```categories``` file:

```
200000 schedule schedule                                                                                                                                                                     
200100 scheduleq schedule-quick-form                                                                                                                                                         
200800 term long-term-schedule                                                                                                                                                               
201000 day memorial-day                                                                                                                                                                      
220000 todo ToDo                                                                                                                                                                             
220100 todoq ToDo-quick-form                                                                                                                                                                 
000000 memo memo-memo                                                                                                                                                                        
000100 memoq memo-quick-form                                                                                                                                                                 
100000 private phone-private                                                                                                                                                                 
100100 privateq phone-private-quick-form
110000 business phone-business
110100 businessq phone-business-quick-form
001000 note/train memo-train
002000 note/family memo-family
003000 note/card memo-credit-card
```

Note that I removed the following: 
```
600000 sheet easy-sheet
700000 addin addin
```

When I included the categories above and attempt a sync, I get the following error:
```
abraham@abraham-hpt510thinclient:~/pv2/conf$ pvlink -S ~/pv2

# pvlink v.2.11 (Nov.17,2003) (ActiveSync, 4MB Flash)
# Copyright (C) 1998,2003 by NARITA Tomio <nrt@ff.iij4u.or.jp>
# All rights reserved. ABSOLUTELY NO WARRANTY!

Conditions:
        Device: /dev/ttyS0
        Folder: /home/abraham/pv2
        Speed:  38400

Just a moment...
Ready to Synchronize
Type = PV-S250 (compatible)
Starting: Synchronize
Syncing: schedule
Syncing: scheduleq
Syncing: term
Syncing: day
Syncing: todo
Syncing: todoq
Syncing: memo
Syncing: memoq
Syncing: private
Syncing: privateq
caleidlink: cannot find object (000053) in host catalog
caleidlink: cannot find object (000054) in host catalog
caleidlink: cannot find object (000055) in host catalog
caleidlink: cannot find object (000056) in host catalog
caleidlink: cannot find object (000057) in host catalog
caleidlink: cannot find object (000058) in host catalog
caleidlink: cannot find object (000059) in host catalog
caleidlink: cannot find object (00005A) in host catalog
caleidlink: cannot find object (00005B) in host catalog
caleidlink: cannot find object (00005C) in host catalog
caleidlink: cannot find object (00005D) in host catalog
caleidlink: cannot find object (00005E) in host catalog
caleidlink: cannot find object (00005F) in host catalog
Syncing: business
Syncing: businessq
Syncing: note/train
Syncing: note/family
Syncing: note/card
Checking: sheet
Saving: /home/abraham/pv2

caleidlink: Sorry, failed to Synchronize.

```

Do you know what further steps I should take to be able to sync addins and/or sheets? Any help would be appreciated. Thanks in advance!

Regards,
Abraham (Jon) Moller
